"""------GRAPH PROPERTIES------"""
LEFT_MARGIN_COLOR = 'r'
RIGHT_MARGIN_COLOR = 'g'
CENTRE_LINE_COLOR = 'b'
CENTRE_LINE_STYLE = '-'
MARGIN_LINE_STYLE = ':'
DEFAULT_X_LABEL = 'Imbalance (MW)'

"""------REPORT PROPERTIES-----"""
PLUS_MINUS = u'\u00b1'
HEADER_FIGURE_X = 170
HEADER_FIGURE_Y = 1
HEADER_FIGURE_WIDTH = 40
HEADER_FIGURE_LOCATION = '../resources/rcc_logo.png'
ALL_DATA_KEYWORD = 'all'
POSITIVE_DATA_KEYWORD = '+'
NEGATIVE_DATA_KEYWORD = '-'
DET_DESCRIPTION_KEYWORD = 'Det.'
DETERMINISTIC_FIGURE_NAME = 'deterministic_results.png'
MC_DESCRIPTION_KEYWORD = 'MC'
MC_FIGURE_NAME = 'mc_results.png'
DATE_FORMAT_FOR_REPORT = "%d.%m.%Y"
TEXT_FONT_SIZE = 12
FONT_FAMILY = 'Helvetica'
HEADING_FONT_SIZE = 20
SUBHEADING_FONT_SIZE = 16
UNDER_SUBHEADING_FONT_SIZE = 14

"""-----FRCE CONSTANTS---"""
FRCE_LEVEL_1_POWER = 35
FRCE_LEVEL_1_PERCENTAGE = 30
FRCE_LEVEL_1_UNIT = 'MW'
FRCE_LEVEL_2_POWER = 65
FRCE_LEVEL_2_PERCENTAGE = 5
FRCE_LEVEL_2_UNIT = 'MW'

"""-----ANALYSIS PROPERTIES-----"""
NOT_EARLIER_THAN_SIX_MONTHS = 6
AT_LEAST_ONE_FULL_YEAR_PERIOD = 1
TIME_FORMAT = "%Y-%m-%dT%H:%MZ"
START_DATE_KEYWORD = 'start_date'
END_DATE_KEYWORD = 'end_date'
MEAN_KEYWORD = 'mean'
SUM_KEYWORD = 'sum'
STD_KEYWORD = 'std'
SAMPLING_TIME = '15min'
REGIONS = ['Baltics']

"""-----TEST PROPERTIES-----"""
INPUT_DATA_FIGURE_NAME = 'input_data.png'
INITIAL_ALLOWED = 'Max. allowed'
INITIAL_UNCORRECTED = "Actual"
TARGET = 'target'
LOWER_BOUND = 'lower value'
UPPER_BOUND = 'upper value'
EXCESS_WHEN_APPLIED = 'after applying'
